# Generated by Django 2.2.5 on 2019-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='front_image',
            field=models.ImageField(default='', upload_to='posts'),
            preserve_default=False,
        ),
    ]
